name: eps_client
description: "EPS-Client"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #routing
  go_router: ^16.0.0

  #riverpod:
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  #localization:
  easy_localization: ^3.0.7+1

  #network:
  dio: ^5.8.0+1

  #http:
  http: ^1.4.0

  #cached_network_image:
  cached_network_image: ^3.4.1

  #get_storage:
  get_storage: ^2.1.1

  #flutter_spinkit:
  flutter_spinkit: ^5.2.1

  #geolocator:
  geolocator: ^14.0.2

  #geocoding:
  geocoding: ^4.0.0

  #dropdown_button2:
  dropdown_button2: ^2.3.9

  #flutter_bounceable:
  flutter_bounceable: ^1.2.0

  #loading_indicator:
  loading_indicator: ^3.1.1

  #firebase:
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.1.1
  firebase_analytics: ^11.2.0
  firebase_remote_config: ^5.5.0

  #image_picker:
  image_picker: any

  #google_mlkit_text_recognition:
  google_mlkit_text_recognition: any
  google_mlkit_commons: ^0.11.0

  #camerawesome
  camerawesome: ^2.5.0

  #file_picker:
  file_picker: ^10.3.3

  #pin_code_fields:
  pin_code_fields: ^8.0.1

  #intl_phone_field:
  intl_phone_field: ^3.2.0

  #google_sign_in:
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1

  #envied:
  envied: ^1.3.1



  #intl:
  intl: ^0.20.2
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  custom_lint:
  riverpod_lint:
  riverpod_generator:
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true

  #---------------- ./ LOCAL ASSETS ----------------#
  assets:
    - assets/images/
    - assets/svgs/

  #---------------- ./ LOCAL FONTS ----------------#
#  fonts:
#    - family: Jaldi
#      fonts:
#        - asset: fonts/jaldi_regular.ttf
